<?php

use Nette\Application\Routers\Route;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/libs/functions.php';

// Configure application
$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode($configurator::AUTO);
$configurator->enableDebugger(__DIR__ . '/log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
if (file_exists($localConf = __DIR__ . '/config/config.local.neon')) {
	$configurator->addConfig($localConf, $configurator::NONE);
}

// create container
return $configurator->createContainer();
